### PR TITLE
Possible fix for react native support

### PR DESCRIPTION
**Pull request by Jonatthu**
image

### CODE REVIEW

**Comment by Jonatthu** [comment]
For unblock yourself declare on the App.tsx

import { AppCore } from '@app/core';
import React from 'react';

import './PlatformImports';
import { Platform } from 'react-native';

// Temporal fix for datepicker
if (Platform.OS === 'ios') {
	window.addEventListener = function (a, b) {};
	window.removeEventListener = function (a, b) {};
}

export default function App() {
	return <AppCore />;
}

// import Storybook from './storybook/index';
// export default Storybook;

// if (Platform.OS !== 'web') {
// 	NativeModules.DevSettings.setIsDebuggingRemotely(true);
// }

**Comment by Jonatthu** [comment]
image

It is a work in progress for better ui but with this lib it is really cool to build this... 🗡️

**Comment by Jonatthu** [comment]
image

**Comment by tresko** [comment]
Nice one, thank you very much :)

**Pull request merged**
